// lang.h — Sprachauswahl für TigoServer Web-Oberfläche
// Sprache hier festlegen, dann neu kompilieren:
#define LANG_DE
// #define LANG_EN   // Alternativ: diese Zeile aktivieren statt LANG_DE

#ifdef LANG_DE

  #define TXT_NAV_HOME        "🏠 Home"
  #define TXT_NAV_DEBUG       "🧠 Debug"
  #define TXT_NAV_PANELS      "🔖 Panels"
  #define TXT_NAV_SPIFFS      "💾 SPIFFS"
  #define TXT_NAV_REBOOT      "🔁 Reboot"
  #define TXT_CONFIRM_REBOOT  "Neu starten?"

  #define TXT_SPIFFS_TITLE       "Dateien"
  #define TXT_SPIFFS_COL_NAME    "Name"
  #define TXT_SPIFFS_COL_SIZE    "Größe"
  #define TXT_SPIFFS_NOFILES     "Keine Dateien"
  #define TXT_SPIFFS_DOWNLOAD    "⬇ Download"
  #define TXT_SPIFFS_DELETE      "✕ Löschen"
  #define TXT_SPIFFS_CONFIRM_DEL "löschen?"
  #define TXT_SPIFFS_STORAGE     "Speicher"
  #define TXT_SPIFFS_USED        "belegt"
  #define TXT_SPIFFS_FREE        "frei:"
  #define TXT_SPIFFS_FREE_RAM    "freier RAM:"
  #define TXT_SPIFFS_UPLOAD_H    "Datei hochladen"
  #define TXT_SPIFFS_UPLOAD_LBL  "Datei zum Hochladen auf SPIFFS auswählen:"
  #define TXT_SPIFFS_UPLOAD_BTN  "⬆ Hochladen"

  #define TXT_PANELS_HEADING     "Panel-Zuordnung"
  #define TXT_PANELS_NODES       "Knoten"
  #define TXT_PANELS_DESC1       "Weise jedem Panel-Long-Address eine Bezeichnung zu (z.B. A4). Die Bezeichnung wird per WebSocket im Feld"
  #define TXT_PANELS_DESC2       "übertragen."
  #define TXT_PANELS_EMPTY       "Kein Knoten in NodeTable. Warte, bis sich die Panels verbinden."
  #define TXT_PANELS_COL_LONGADDR "Long Address"
  #define TXT_PANELS_COL_ADDR     "Addr"
  #define TXT_PANELS_COL_CURRENT  "Aktuelle Bezeichnung"
  #define TXT_PANELS_COL_SET      "Festlegen"
  #define TXT_PANELS_UNASSIGNED   "nicht zugewiesen"
  #define TXT_PANELS_PLACEHOLDER  "z.B. A4"
  #define TXT_PANELS_SAVE         "✓ Speichern"
  #define TXT_PANELS_REMOVE       "× Entfernen"
  #define TXT_PANELS_CONFIRM_REM  "Bezeichnung"
  #define TXT_PANELS_CONFIRM_REM2 "entfernen?"
  #define TXT_PANELS_MAPPING_H    "Gespeicherte Zuordnung"
  #define TXT_PANELS_ENTRIES      "Einträge"
  #define TXT_PANELS_NOMAPPING    "Keine Zuordnung gespeichert."
  #define TXT_PANELS_COL_LABEL    "Bezeichnung"
  #define TXT_PANELS_CONFIRM_REM3 "Entfernen?"

  #define TXT_DEBUG_DEVICES_H    "Tigo-Geräte"
  #define TXT_DEBUG_COL_PANEL    "Panel"
  #define TXT_DEBUG_COL_NODEID   "Node ID"
  #define TXT_DEBUG_COL_STROM    "Strom"
  #define TXT_DEBUG_COL_WATT     "Watt"
  #define TXT_DEBUG_COL_TEMP     "Temp"
  #define TXT_DEBUG_COL_SLOT     "Slot"
  #define TXT_DEBUG_NODETABLE_H  "Node Table"
  #define TXT_DEBUG_UNSAVED      "⚠️ NodeTable geändert und noch nicht gespeichert"
  #define TXT_DEBUG_SAVE_NOW     "💾 NodeTable jetzt speichern"

  #define TXT_ERR_INVALID_LABEL  "Ungültige Bezeichnung: nur Buchstaben, Ziffern, - _ . Leerzeichen (max. 20 Zeichen)"
  #define TXT_ERR_DELETE_FILE    "Fehler beim Löschen der Datei"
  #define TXT_ERR_FILE_NOTFOUND  "Datei nicht gefunden"
  #define TXT_ERR_MISSING_PARAM  "Fehlender Parameter: file"
  #define TXT_REBOOTING          "♻️ ESP32 wird neu gestartet..."
  #define TXT_SAVED_VIA_ENDPOINT "✅ NodeTable über /save-Endpunkt gespeichert"
  #define TXT_404                "404: Nicht gefunden"
  #define TXT_ERR_INVALID_FNAME  "❌ Ungültiger Dateiname."
  #define TXT_ERR_FNAME_TOOLONG  "❌ Dateiname zu lang."
  #define TXT_ERR_NO_SPACE       "❌ Nicht genug Speicherplatz auf SPIFFS."

#else // LANG_EN

  #define TXT_NAV_HOME        "🏠 Home"
  #define TXT_NAV_DEBUG       "🧠 Debug"
  #define TXT_NAV_PANELS      "🔖 Panels"
  #define TXT_NAV_SPIFFS      "💾 SPIFFS"
  #define TXT_NAV_REBOOT      "🔁 Reboot"
  #define TXT_CONFIRM_REBOOT  "Restart device?"

  #define TXT_SPIFFS_TITLE       "Files"
  #define TXT_SPIFFS_COL_NAME    "Name"
  #define TXT_SPIFFS_COL_SIZE    "Size"
  #define TXT_SPIFFS_NOFILES     "No files"
  #define TXT_SPIFFS_DOWNLOAD    "⬇ Download"
  #define TXT_SPIFFS_DELETE      "✕ Delete"
  #define TXT_SPIFFS_CONFIRM_DEL "?"
  #define TXT_SPIFFS_STORAGE     "Storage"
  #define TXT_SPIFFS_USED        "used"
  #define TXT_SPIFFS_FREE        "free:"
  #define TXT_SPIFFS_FREE_RAM    "free RAM:"
  #define TXT_SPIFFS_UPLOAD_H    "Upload file"
  #define TXT_SPIFFS_UPLOAD_LBL  "Select a file to upload to SPIFFS:"
  #define TXT_SPIFFS_UPLOAD_BTN  "⬆ Upload"

  #define TXT_PANELS_HEADING     "Panel Mapping"
  #define TXT_PANELS_NODES       "nodes"
  #define TXT_PANELS_DESC1       "Assign a label (e.g. A4) to each panel's long address. The label is transmitted via WebSocket in the field"
  #define TXT_PANELS_DESC2       "."
  #define TXT_PANELS_EMPTY       "No node in NodeTable yet. Wait for the panels to connect."
  #define TXT_PANELS_COL_LONGADDR "Long Address"
  #define TXT_PANELS_COL_ADDR     "Addr"
  #define TXT_PANELS_COL_CURRENT  "Current Label"
  #define TXT_PANELS_COL_SET      "Set"
  #define TXT_PANELS_UNASSIGNED   "unassigned"
  #define TXT_PANELS_PLACEHOLDER  "e.g. A4"
  #define TXT_PANELS_SAVE         "✓ Save"
  #define TXT_PANELS_REMOVE       "× Remove"
  #define TXT_PANELS_CONFIRM_REM  "Remove label"
  #define TXT_PANELS_CONFIRM_REM2 "?"
  #define TXT_PANELS_MAPPING_H    "Saved Mapping"
  #define TXT_PANELS_ENTRIES      "entries"
  #define TXT_PANELS_NOMAPPING    "No mapping saved."
  #define TXT_PANELS_COL_LABEL    "Label"
  #define TXT_PANELS_CONFIRM_REM3 "Remove?"

  #define TXT_DEBUG_DEVICES_H    "Tigo Devices"
  #define TXT_DEBUG_COL_PANEL    "Panel"
  #define TXT_DEBUG_COL_NODEID   "Node ID"
  #define TXT_DEBUG_COL_STROM    "Current"
  #define TXT_DEBUG_COL_WATT     "Watt"
  #define TXT_DEBUG_COL_TEMP     "Temp"
  #define TXT_DEBUG_COL_SLOT     "Slot"
  #define TXT_DEBUG_NODETABLE_H  "Node Table"
  #define TXT_DEBUG_UNSAVED      "⚠️ NodeTable changed and not yet saved"
  #define TXT_DEBUG_SAVE_NOW     "💾 Save NodeTable now"

  #define TXT_ERR_INVALID_LABEL  "Invalid label: only letters, digits, - _ . space allowed (max. 20 chars)"
  #define TXT_ERR_DELETE_FILE    "Error deleting file"
  #define TXT_ERR_FILE_NOTFOUND  "File not found"
  #define TXT_ERR_MISSING_PARAM  "Missing parameter: file"
  #define TXT_REBOOTING          "♻️ Rebooting ESP32..."
  #define TXT_SAVED_VIA_ENDPOINT "✅ NodeTable saved via /save endpoint"
  #define TXT_404                "404: Not Found"
  #define TXT_ERR_INVALID_FNAME  "❌ Invalid filename."
  #define TXT_ERR_FNAME_TOOLONG  "❌ Filename too long."
  #define TXT_ERR_NO_SPACE       "❌ Not enough space on SPIFFS."

#endif
